version: "2"

services:
  iri:
    container_name: iota_iri
    image: perfectstorm85/rock64_iota_iri:v1.5.5
    hostname: iri
    restart: unless-stopped
    environment:
      - JAVA_MAX_MEMORY=3500m
      - JAVA_MIN_MEMORY=256m
      - DOCKER_IRI_MONITORING_API_PORT_ENABLE=1
      - DOCKER_IRI_MONITORING_API_PORT_DESTINATION=14265
      - DOCKER_IRI_MONITORING_API_PORT_LOCATION=14266
      - DOCKER_IRI_REMOTE_LIMIT_API={"interruptAttachToTangle, attachToTangle, addNeighbors, removeNeighbors, getNeighbors"}
    expose:
      - "5556"
    volumes:
      - ./volumes/iri/iota.ini:/iri/iota.ini:ro
      - ./volumes/iri/ixi:/iri/ixi:rw
      - ./volumes/iri/mainnetdb:/iri/mainnetdb:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "14600:14600/udp"
      - "15600:15600/tcp"
      - "14265:14265"
    command: ["-c","/iri/iota.ini"]
    logging:
      options:
        max-size: 1m
    
  nelson.cli:
    container_name: iota_nelson.cli
    image: perfectstorm85/rock64_nelson.cli:latest
    hostname: nelson.cli
    restart: unless-stopped
    volumes:
      - ./volumes/nelson.cli/data:/data:rw
      - ./volumes/nelson.cli/config.ini:/home/node/config.ini:ro
      - /etc/localtime:/etc/localtime:ro
    command: "--config /home/node/config.ini"
    ports:
      - "18600:18600"
      - "16600:16600"
    logging:
      options:
        max-size: 1m

  nelson.gui:
    container_name: iota_nelson.gui
    image: perfectstorm85/rock64_nelson.gui:latest
    hostname: nelson.gui
    restart: unless-stopped
    command: "-p 5000 --apiHostname nelson.cli --apiPort 18600"
    ports:
      - "5000:5000"
    logging:
      options:
        max-size: 1m

  field.cli:
    container_name: iota_field.cli
    image: perfectstorm85/rock64_field.cli:latest
    hostname: field.cli
    restart: unless-stopped
    volumes:
      - ./volumes/field.cli/config.ini:/usr/src/field/config.ini:ro
      - ./volumes/field.cli/root:/root
      - /etc/localtime:/etc/localtime:ro
    command: "--config /usr/src/field/config.ini"
    ports:
      - "21310:21310"
    logging:
      options:
        max-size: 1m
